name: Daily Market Update Bot

on:
  schedule:
    # Run at 5:00 PM IST (11:30 AM UTC) on weekdays
    - cron: '30 11 * * 1-5'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-market-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run market bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python market_bot.py
        
    - name: Log completion
      run: echo "Market update completed at $(date)"
